openapi: 3.0.0

info:
    title: OTX Alienvault API
    description: OTX Alienvault API
    version: "v1"

servers:
    - url: https://otx.alienvault.com/

paths:
    /api/v1/indicators/domains/{domain}/general:
        get:
            operationId: OTXAlienvaultDomainInformation
            summary: Lookup domain information
            parameters:
                - in: path
                  name: domain
                  schema:
                      type: string
                  required: true
                  description: The domain address to lookup
            responses:
                "200":
                    description: OK
